export const countryData = [
  { label: "Nigeria", value: "NGA" },
  { label: "Russia", value: "RUS" },
  { label: "Ghana", value: "GHA" },
  { label: "China", value: "china" },
  { label: "China", value: "china" },
  { label: "China", value: "china" },
  { label: "China", value: "china" },
  { label: "China", value: "china" },
  { label: "China", value: "china" },
  { label: "China", value: "china" },
  { label: "China", value: "china" },
  { label: "China", value: "china" },
  { label: "China", value: "china" },
  { label: "China", value: "china" },
];
