export const countryData = [
  { label: "Nigeria", value: "nigeria" },
  { label: "Ghana", value: "ghana" },
  { label: "China", value: "china" },
  { label: "China", value: "china" },
  { label: "China", value: "china" },
  { label: "China", value: "china" },
  { label: "China", value: "china" },
  { label: "China", value: "china" },
  { label: "China", value: "china" },
  { label: "China", value: "china" },
  { label: "China", value: "china" },
  { label: "China", value: "china" },
  { label: "China", value: "china" },
];
